### ISSUE TITLE
Deprecate Reader.byteValue() in favor of a new Reader.uInt8ArrayValue() method

### ISSUE THREAD

**Issue by pbcornell** [amazon-ion/ion-js#559]
src/dom/Value.ts provides a clearer `uInt8ArrayValue(): Uint8Array | null` method; consider updating the `Reader` interface to follow suit.

**Comment by desaikd** [comment]
Remove the deprecated method for `v5.0.0` release.

**Comment by desaikd** [comment]
Fixed with #750
