### ISSUE TITLE
Add an allElements() method alongside elements()

### ISSUE THREAD

**Issue by zslayton** [amazon-ion/ion-js#693]
v4.2.0 added support for structs with repeated field names, e.g.
```js
{
  foo: 1,
  foo: true,
  foo: bar
}
```
To preserve backwards compatibility, existing struct accessor methods (`get`, `fields`) continued to return deduplicated results, using the value associated with the last appearance of each field name. New flavors of those methods (`getAll`, `allFields`) were added that would instead return an array with every value associated each field name. 

We have not yet added an `allElements` method for the `elements` method. A call to `elements` with the sample struct above would return `[bar]` while the `allElements` method would return `[1, true, bar]`.

**Comment by desaikd** [comment]
Express `allElements()` behavior in `elements()` with `v5.0.0` release.

**Comment by desaikd** [comment]
fixed with #754
