### ISSUE TITLE
`package.json` should use conditional exports

### ISSUE THREAD

**Issue by neeerp** [amazon-ion/ion-js#740]
This package ships with multiple builds, however only the cjs build is exposed in the [package.json](https://github.com/amazon-ion/ion-js/blob/ff9741053918df9d918d4e667f62e1a8d570cc5b/package.json#L5-L6). I think using [conditional exports](https://nodejs.org/api/packages.html#conditional-exports) would resolve to the es6 build when using `import` and the `cjs` build when using `require`.

**Comment by jobarr-amzn** [comment]
Resolved by #741 .
