### ISSUE TITLE
The ion-test-driver PR approval workflow is consistently failing

### ISSUE THREAD

**Issue by jobarr-amzn** [amazon-ion/ion-js#742]
See e.g. 
* #721 
* #723 
* #726
* #727
* #741 

Seems like a Python/setup problem. Related to the new Python C bindings, perhaps? Error message coming back is:
```plain
amazon.ion.exceptions.IonException: IERR_INVALID_ARG assertion failed: len == 1
```

**Comment by cheqianh** [comment]
For reference, this issue relates to https://github.com/amazon-ion/ion-python/issues/218

**Comment by jobarr-amzn** [comment]
Fixed by: https://github.com/amazon-ion/ion-test-driver/pull/27
