### ISSUE TITLE
Allow `Decimal`'s constructor to take a `Number` or `String`.

### ISSUE THREAD

**Issue by zslayton** [amazon-ion/ion-js#745]
See [this discussion](https://github.com/amazon-ion/ion-js/issues/739#issuecomment-1452082971).

Constructing a `dom.Decimal` (which is typically what users want) from a number or string cannot be done in a single step unless you use `ion.load(...)`, which is overkill. 

`Value.from(...)` doesn't work. Because there is no hinting system (#620), `Value.from` will never return a `dom.Decimal`; a `String` maps to a `dom.String`, an integer `Number` maps to a `dom.Integer`, and a non-integer `Number` maps to a `dom.Float`.

**Comment by desaikd** [comment]
Fixed with #746
